sudo: required
matrix:
  include:
    - language: python
      python:
        - '2.7'
      install:
        - pip install tox-travis
      script: tox
    
    - language: scala
      scala: 
        - '2.12'
      script: cd aoc_scala && sbt clean test
