name: Scala CI
on:
  push:
    branches:
        - master
  pull_request:
    branches:
        - master
defaults:
  run:
    working-directory: aoc_scala
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: sbt clean test
